CREATE TABLE PRIMARY_KEY_WITH_UNIQUE_INDEX (
  ID INT PRIMARY KEY,
  FIRST_COLUMN INT,
  SECOND_COLUMN INT,
  THIRD_COLUMN INT
);

CREATE UNIQUE INDEX IDX_PRIMARY_KEY_WITH_UNIQUE ON PRIMARY_KEY_WITH_UNIQUE_INDEX(FIRST_COLUMN, SECOND_COLUMN);